import scrapy
from scrapy import Request

class MykboSpider(scrapy.Spider):
    name = "gameid_spider"
    allowed_domains = ["mykbostats.com"]
    start_urls = ["https://mykbostats.com/schedule"]
    
    def parse(self, response):
        # Check if driver (Selenium) is sent with the request.meta
        if response.meta['driver'] is not None:
            # Read the browsers user-agent to check that we havent been blocked
            driver = response.meta['driver']
            user_agent = driver.execute_script("return navigator.userAgent;")
            self.logger.info(f"[parse] User-Agent: {user_agent}")
            
            if response.meta['driver_response'] is not None:
                # Print the actual HTML source code of the HtmlResponse generated by Selenium
                driver_response = response.meta['driver_response']
                self.logger.info("[parse] === page source ===\n{}".format(driver_response.text))
            
            games = response.css('a.game-line')
            self.logger.info(f"[parse] Found {len(games)} games")
            items = []
            for game in games:
                game_id = game.attrib['id'].split('-')[-1]  # Extract the game ID (just the number after 'game-line-')
                item = {
                    'game_id': game_id
                }
                items.append(item)
            
            # yield items
            for item in items:
                yield item